object Versions {
    // Project
    const val AGP = "7.3.1"
    const val KOTLIN = "1.8.0"
    const val HILT = "2.43.2"
    const val GOOGLE_SERVICES = "4.3.15"
    const val FIREBASE_CRASHLYTICS = "2.9.4"

    // Module
    const val ANDROID_CORE_KTX = "1.9.0"
    const val ACTIVITY_COMPOSE = "1.6.1"
    const val MATERIAL3 = "1.0.0-alpha05"
    const val MATERIAL = "1.3.1"
    const val COMPOSE = "1.3.3"
    const val APPCOMPAT = "1.6.1"

    // Test
    const val JUNIT_PLATFORM = "1.9.2"
    const val ASSERTJ = "3.24.2"
    const val UI_TEST_JUNIT4 = "1.3.3"
    const val JUNIT_JUPITER_PARAMS = "5.9.2"
    const val JUNIT = "1.1.5"
    const val ESPRESSO_CORE = "3.5.1"

    const val NAVIGATION_COMPOSE = "2.5.3"
    const val NAVER_MAP_COMPOSE = "1.2.3"
    const val NAVER_SDK = "3.16.1"
    const val PLAY_SERVICES_LOCATION = "21.0.1"
    const val LIFECYCLE = "2.6.1"
    const val ACCOMPANIST = "0.29.1-alpha"
    const val ACCOMPANIST_SYSTEMUICONTROLLER = "0.28.0"
    const val COIL_COMPOSE = "2.2.2"
    const val GLIDE_COMPOSE = "1.0.0-alpha.1"
    const val GLIDE_OKHTTP3 = "4.11.0"
    const val GLIDE_COMPILER = "4.14.2"
    const val GSON = "2.10.1"
    const val KAKAO_LOGIN = "2.12.1"
    const val FIREBASE_BOM = "31.2.3"
    const val FIREBASE_CRASHLYTICS_KTX = "18.3.5"
    const val FIREBASE_ANALYTICS_KTX = "21.2.0"
    const val LOTTIE = "6.0.0"
    const val DAGGER = "2.43.2"
    const val HILT_NAVIGATION_COMPOSE = "1.0.0"
    const val DATASTORE = "1.0.0"
    const val PAGING = "3.1.1"
    const val PAGING_COMPOSE = "1.0.0-alpha18"
    const val RETROFIT = "2.9.0"
    const val OKHTTP3 = "5.0.0-alpha.3"
    const val ROOM = "2.5.0"
}